version: "3.8"

services:
  ammds:
    image: qyg2297248353/ammds:v1.6.31
    container_name: ammds
    ports:
      - "${ammds_app_port}:80"
    volumes:
      - ${TRIM_APPDEST_VOL}/@appshare/ammds/data:/ammds/data
      - ${TRIM_APPDEST_VOL}/@appshare/ammds/db:/ammds/db
      - ${TRIM_APPDEST_VOL}/@appshare/ammds/download:/ammds/download
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_PASS=${ammds_admin_password}
  